### ISSUE TITLE
Support for additional voices?

### ISSUE THREAD

**Issue by sion42x** [usefulsensors/ai_in_a_box#5]
Hi all,

I'm experimenting with voices from https://github.com/rhasspy/piper/blob/master/VOICES.md, and specifically trying out a couple of the 'medium' quality voices. When running them through piper standalone, the voices sound good with the default .json file. However, through tts.py the voices are extremely slow and sound like the Nina/Alexander chimera from Fullmetal Alchemist which brings back a lot of painful memories.

I've tried modifying the len_scale, but even when I can make it faster the pitch is far too low. Am I missing anything to be able to use a different voice? Here are the voices I'm currently trying in the `./downloaded` folder.

```
-rw-rw-r-- 1 steve steve   63531379 Mar 12 11:07 en_US-kristin-medium.onnx
-rw-rw-r-- 1 steve steve       4971 Apr  5 10:59 en_US-kristin-medium.onnx.json
-rw-rw-r-- 1 steve steve      20124 Apr  5 10:40 en_US-libritts_r-medium.onnx.json
-rw-rw-r-- 1 steve steve   78580914 Sep 23  2023 en_US-libritts_r-medium.onnx
-rw-rw-r-- 1 steve steve       4169 Apr  5 10:39 en_US-kathleen-low.onnx.json
-rw-rw-r-- 1 steve steve   63104526 Jun 26  2023 en_US-kathleen-low.onnx
```

**Comment by guynich** [comment]
Interesting work!

I think your choice of models generate audio with a higher [audio`sample_rate`](https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kristin/medium/en_US-kristin-medium.onnx.json?download=true.json) than [AI in a Box supports see tts.py](https://github.com/usefulsensors/ai_in_a_box/blob/e4e327ec37d7a2dbf46a90e1aff9c966141b1969/tts.py#L19).  

This should explain why these models have a higher quality standalone and why the speech runs slower with AI in a Box default rate of 16000 Hz.  AI in a Box does not support running at a higher sample rate.   If you want to look further into this I think you could try adding sample rate conversion code and see if that helps.

Let us know how you get on with this.
Guy

**Comment by guynich** [comment]
You can also try setting `tts.py` rate to match your choice of models (see their config files) but I don't know if that will work or not.  Quicker than sample rate conversion code.

**Comment by sion42x** [comment]
Thanks @guynich this is great! I'll give it a shot.

Is there a discord or anything for the AI in a Box and your other projects? I'd love to collaborate further and show off my DIY Orange Pi 5 Plus build using Zephyr 3B (soon to be a Phi-3 finetune).
